### ISSUE TITLE
请教xlucifer.top相册程序可以分享吗

### ISSUE THREAD

**Issue by notemx** [X-Lucifer/X-Lucifer#1]
大佬，请教xlucifer.top相册程序可以分享吗

**Comment by X-Lucifer** [comment]
[主页源码.zip](https://github.com/X-Lucifer/X-Lucifer/files/7317210/default.zip)


> 大佬，请教xlucifer.top相册程序可以分享吗

**Comment by notemx** [comment]
谢谢！
